version: "3"
services:
 
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - ./jenkins/home:/home  
      - /var/run/docker.sock:/var/run/docker.sock
 
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.example.com'
    ports:
      - '8081:80'
      - '443:443'
      - '2224:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
 
  artifactory: # docker run --name artifactory -p 8081:8081 -v ./artifactory:/var/opt/jfrog/artifactory docker.bintray.io/jfrog/artifactory-pro:latest
    image: 'docker.bintray.io/jfrog/artifactory-pro:latest' 
    ports:
      - '8082:8081'
    volumes:
      - './artifactory:/var/opt/jfrog/artifactory'
#    environment: #    Add extra Java options by uncommenting the following lines
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
